### ISSUE TITLE
failed tests following $make test

### ISSUE THREAD

**Issue by alecristia** [bootphon/wordseg#12]
Tried on iMac.

# output from $ make test

Running tests...
Test project /Users/alejandrinacristia/gitrepos/wordseg/build
      Start  1: wordseg.test_ag.py
 1/13 Test  #1: wordseg.test_ag.py .................***Failed    4.02 sec
      Start  2: wordseg.test_dpseg.py
 2/13 Test  #2: wordseg.test_dpseg.py ..............***Failed    0.37 sec
      Start  3: wordseg.test_eval.py
 3/13 Test  #3: wordseg.test_eval.py ...............   Passed    0.29 sec
      Start  4: wordseg.test_folding.py
 4/13 Test  #4: wordseg.test_folding.py ............   Passed    2.07 sec
      Start  5: wordseg.test_pipeline.py
 5/13 Test  #5: wordseg.test_pipeline.py ...........***Failed    0.37 sec
      Start  6: wordseg.test_prepare.py
 6/13 Test  #6: wordseg.test_prepare.py ............   Passed    0.35 sec
      Start  7: wordseg.test_puddle.py
 7/13 Test  #7: wordseg.test_puddle.py .............***Failed    0.36 sec
      Start  8: wordseg.test_separator.py
 8/13 Test  #8: wordseg.test_separator.py ..........   Passed    0.30 sec
      Start  9: wordseg.test_stats.py
 9/13 Test  #9: wordseg.test_stats.py ..............   Passed    4.21 sec
      Start 10: wordseg.test_tp.py
10/13 Test #10: wordseg.test_tp.py .................   Passed    0.30 sec
      Start 11: wordseg.test_tutorial.py
11/13 Test #11: wordseg.test_tutorial.py ...........***Failed    0.47 sec
      Start 12: wordseg.test_utils.py
12/13 Test #12: wordseg.test_utils.py ..............***Failed    1.83 sec
      Start 13: wordseg.test_wordseg_commands.py
13/13 Test #13: wordseg.test_wordseg_commands.py ...***Failed    0.80 sec

46% tests passed, 7 tests failed out of 13

Total Test time (real) =  15.78 sec

The following tests FAILED:
	  1 - wordseg.test_ag.py (Failed)
	  2 - wordseg.test_dpseg.py (Failed)
	  5 - wordseg.test_pipeline.py (Failed)
	  7 - wordseg.test_puddle.py (Failed)
	 11 - wordseg.test_tutorial.py (Failed)
	 12 - wordseg.test_utils.py (Failed)
	 13 - wordseg.test_wordseg_commands.py (Failed)
Errors while running CTest
make: *** [test] Error 8

# output from previous command $ cmake ..
-- The C compiler identification is AppleClang 9.0.0.9000038
-- The CXX compiler identification is AppleClang 9.0.0.9000038
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Project is wordseg-0.5.1
-- Setting build type to Release
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
-- Option AG_QUADRUPLE is OFF
-- Option AG_PARALLEL is OFF
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
-- Found PythonInterp: /anaconda/bin/python (found version "2.7.13") 
-- Found PythonLibs: /anaconda/lib/libpython2.7.dylib (found version "2.7.13") 
-- Python is /anaconda/bin/python
-- Found Sphinx as /anaconda/bin/sphinx-build
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/alejandrinacristia/gitrepos/wordseg/build

**Comment by mmmaat** [comment]
Did you run **make** and **make install** after *cmake ..* and before *make test*? Did it success?
After that can you run **pytest -v test/** instead of make test to have more details please?

**Comment by mmmaat** [comment]
Moreover you are welcomed to use Python3 instead of Python2... Better, safer, faster.

The lines from your cmake output.
```
-- Found PythonInterp: /anaconda/bin/python (found version "2.7.13")
-- Found PythonLibs: /anaconda/lib/libpython2.7.dylib (found version "2.7.13")
```
