### ISSUE TITLE
unusual syntax for bash version of dibs?

### ISSUE THREAD

**Issue by alecristia** [bootphon/wordseg#22]
-	cat prepared.txt | wordseg-tp -t absolute > segmented.tpabs.txt #this works
-	cat prepared.txt | wordseg-dibs -t baseline > segmented.dibs_b.txt #this does NOT work

> Error:
> usage: wordseg-dibs [-h] [-v | -q] [-o <output-file>] [-d <output-file>]
>                     [-p <str>] [-s <str>] [-w <str>]
>                     [-t {baseline,phrasal,lexical}] [-T <float>] [-b <float>]
>                     [<input-file>] <train-file>
> wordseg-dibs: error: too few arguments
> 

Notice the type is baseline, which is not supposed to take -b. We can still try it, to no avail:
$ cat prepared.txt | wordseg-dibs -t baseline -b .5 > segmented.dibs_b.txt

> usage: wordseg-dibs [-h] [-v | -q] [-o <output-file>] [-d <output-file>]
>                     [-p <str>] [-s <str>] [-w <str>]
>                     [-t {baseline,phrasal,lexical}] [-T <float>] [-b <float>]
>                     [<input-file>] <train-file>
> wordseg-dibs: error: too few arguments

The only syntax that seemed to work was:
$ wordseg-dibs -t baseline  -o segmented.dibs_b.txt  prepared.txt prepared.txt

If I only give it one input file (the train-file), I get a never-ending wait:
$ wordseg-dibs -t baseline  -o segmented.dibs_b.txt  prepared.txt 
(nothing happens)

**Comment by alecristia** [comment]
Additionally, with that code, dibs makes ZERO cuts in all the files I tested --> I don't think it's working normally.

**Comment by mmmaat** [comment]
dibs is the only algo that requires a train file:

```
usage: wordseg-dibs [-h] [-v | -q] [-o <output-file>] [-d <output-file>] [-p <str>] [-s <str>] [-w <str>]
                    [-t {baseline,phrasal,lexical}] [-T <float>] [-b <float>]
                    [<input-file>] <train-file>
```
* cat prepared.txt | wordseg-dibs -t baseline > segmented.dibs_b.txt
    -> missing train file
* wordseg-dibs -t baseline -o segmented.dibs_b.txt prepared.txt
   -> waits some input on stdin

This is working
-------------------

```
(wordseg) mathieu@deaftone:~/dev/wordseg$ head -200 test/data/phonologic.txt > train.txt
(wordseg) mathieu@deaftone:~/dev/wordseg$ cat test/data/phonologic.txt | wordseg-prep | wordseg-dibs train.txt -t baseline
```
