### ISSUE TITLE
bash exemples for wordseg-ag

### ISSUE THREAD

**Issue by mmmaat** [bootphon/wordseg#23]
We need to have command-line exemples somewhere in the docs, or to improve the --help messages so that they are understandable to newcomers.

**Comment by mmmaat** [comment]
@alecristia is it good idea to add a section with command-line examples in https://wordseg.readthedocs.io/en/latest/bash_reference.html ? Or are you refactoring this part of the docs ?

**Comment by alecristia** [comment]
My goal is to eventually add it to the tutorial and bash reference, so if
you just want to throw it at me, I'll get it added!
​

**Comment by alecristia** [comment]
correction, the tutorial already has a dpseg example -- sorry about that!

**Comment by mmmaat** [comment]
I'm refactoring (simplifying) wordseg-ag command in bash, in order to write a simple exemple.

Is it a good idea to generate a colloc0 grammar automatically when the user doesn't provide one? Or we force the user to have it's grammar ready?

**Comment by mmmaat** [comment]
AG example:
```
# assuming we are in the wordseg root directory
GRAMMAR=data/ag/Colloc0_enFestival.lt
CATEGORY=Colloc0
cat test/data/tagged.txt | wordseg-prep | wordseg-ag  $GRAMMAR $CATEGORY --njobs 4 --verbose > segmented.txt
