### ISSUE TITLE
best way to restructure docs?

### ISSUE THREAD

**Issue by alecristia** [bootphon/wordseg#28]
There is some information that currently appears only in the references (and often only in one reference, either python or bash), but it is common to both python and bash. (e.g. the explanation of the structure of the input text is within the bash reference only, although it applies to both. Explanations for the algorithms are given only in the python reference, but apply to both.) 

I would like to put common information in a section **before** the split bash/python references (which would then be exclusively about how to interact with the module in the two languages).
 
Would you recommend that I just go into the bash/python reference (knowing that in the case of python, that means going into the python subscripts) and: 
1) cut+paste, 
2) copy+paste, or 
3) something else? 

If I copy+paste, that means when we want to make a change to the explanation in the future, we will need to remember to fix it in two places, so that is my least favorite option.

Thank you!

PS: I'll be doing a pull request for my branch new-docs soon. It's 2 commits behind, so it shouldn't be too painful a merge.

**Comment by mmmaat** [comment]
Ok I see... For the docs in *.rst files, you can cut+paste as you want. But for the tutorial.py/tutorial.sh be careful since they are tested with pytest (here it's maybe better just to copy+paste)

for the PR it should be easy no problem!
