### ISSUE TITLE
typo in results output

### ISSUE THREAD

**Issue by alecristia** [bootphon/wordseg#32]
token_recall there twice, token_fscore missing; eg:

token_precision 0.5671
token_recall    0.7108
token_recall    0.6309
type_precision  0.4667
type_recall     0.3502
type_fscore     0.4002
boundary_precision      0.7125
boundary_recall 0.9428
boundary_fscore 0.8117

**Comment by mmmaat** [comment]
This have been fixed by commit https://github.com/bootphon/wordseg/commit/f2594049f9ef7ca8cfcd77ea74011a8e73bddeeb
