### ISSUE TITLE
Syllabification #4 - separators

### ISSUE THREAD

**Issue by GladB** [bootphon/wordseg#39]
There is a problem when stating different phone and word separators (with the parameters -p ' ' -w ';eword' for example), the only case working for me is when there is no phone separator in the file and spaces as word separator (in which case I use "-p '_' -w ' ' "); moreover, it would be useful to be able to specify what the syllable separator should be in the output (it is ";esyll" for now).

**Comment by mmmaat** [comment]
* Indeed, that little exemple fails as we have two word separators at the end:
  ```
  $ echo "n o ;eword" | wordseg-syll cspanish_onsets.txt cspanish_vowels.txt
  n o ;esyll;eword;eword
  ```
  I'm working on it but this is not obvious. Do you have other toy examples like that?

* For the second part of the issue, you can already specify the output syllable separator using the usual `-s` argument:
  ```
  echo "n o ;eword" | wordseg-syll -s "SYLL" cspanish_onsets.txt cspanish_vowels.txt
  n o SYLL;eword;eword
  ```

**Comment by GladB** [comment]
- my examples are a little weird because I had no phone separator (which is why I introduced a "fake" phone separator '_' for the syllabification step), and my word separator was ' ' (which is the phone separator by default), so I don't think I have anything that might be useful for you.
- I just realized that I had this error with the -s argument because I tried to put a space in the syllable separator I think, which is not accepted I guess.

**Comment by mmmaat** [comment]
I fixed the `;eword;eword` problem.

Spaces are supported as syllable separators: 
```
$ echo "n;o;word" | wordseg-syll -p ";" -s " " -w "word" cspanish_onsets.txt cspanish_vowels.txt
n;o; word
```
