### ISSUE TITLE
prepare files does not deal with multibyte

### ISSUE THREAD

**Issue by alecristia** [bootphon/wordseg#42]
I'm not sure whether this is an intentional and desirable limitation, but when some multibyte character is present, wordseg-prep fails returning:
```
fatal error: 'utf-8' codec can't decode byte 0xb5 in position 46: invalid start byte
fatal error: 'utf-8' codec can't decode byte 0xb5 in position 5894: invalid start byte
```

Not sure the following helps, but I note that the error occurs even for characters that pass the first 3 of the next 4 tests (which meant I had to search for a WHILE to find them):

```
egrep '[^a-zA-Z; 0-9]' FILE
grep -P "[\x80-\xFF]" FILE
grep  -axv '.*' FILE
nonascii() { LANG=C grep --color=always '[^ -~]\+'; } ; cat FILE | nonascii
```

**Comment by mmmaat** [comment]
Can you put here the guilty lines of your FILE please ? Thus I will investigate that issue. Thanks.

**Comment by mmmaat** [comment]
For me all is fine and  þ works both in python2 and python3. I added a piece of code (here: https://github.com/bootphon/wordseg/commit/11c9663af0de8f72a680db26cccad9d81e73abb7) to force the input text as utf8, for me this have no effect but maybe for you it will work ?

**Comment by alecristia** [comment]
just in case, here's a fuller list:
toremove=c("«","‡","§","™","•","�","Œ","£","±") 

and some more
ʒ
え
θ
ãāàåå̀ã
 ̟
ʔ
m̄

**Comment by mmmaat** [comment]
I cannot reproduce your bug. Can you try with the latest release (do not forget to `make install` it), and if the problem persists, please give me some context: is it on mac ? what are the results of the following commands?
```
which wordseg-prep
which python
python --version
```

Here the little test I used:
```
cat ./test/data/tagged.txt | sed -e 's|aa|ãā|g' -e 's|ae|ã̟ʔ|g' -e 's|ah|å|g' -e 's|b|�|g' -e 's|ax|£|g' | wordseg-prep
```
