### ISSUE TITLE
provide citation information

### ISSUE THREAD

**Issue by alecristia** [bootphon/wordseg#50]
Here is an example:
@misc{WordSeg,
  author = {Bernard, Mathieu and Cristia, Alejandrina},
  title = {Wordseg},
  year = {2018},
  version = {0.7},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/bootphon/wordseg/tree/master/wordseg}}
}

**Comment by mmmaat** [comment]
Done, see https://wordseg.readthedocs.io/en/latest/
