### ISSUE TITLE
puddle.py NameError, filter_by_frequency function

### ISSUE THREAD

**Issue by francescocabiddu** [bootphon/wordseg#53]
Hi, 
I have tried to run puddle.py on my machine after downloading the package. 
I noticed that in the script the function filter_by_frequency() is commented out. 
As I need puddle to sort chunks by frequency, I tried to reintroduce the function also changing line 106 from:
`# j = filter_by_frequency(utterance,i,j)`
to
` j = self.filter_by_frequency(utterance,i,j)`

However, I keep getting an error saying:
NameError: name 'filter_by_frequency' is not defined

Note that I get the same error even when those sections are commented out. 
Would you be able to suggest a solution? thanks

**Comment by mmmaat** [comment]
Hi,
I guess you have commented out the `filter_by_frequency` function as well: https://github.com/bootphon/wordseg/blob/master/wordseg/algos/puddle.py#L26.

In this case it can be related to installation. If you installed wordseg following [docs](https://wordseg.readthedocs.io/en/latest/installation.html), you need to reinstall it **after the modifications**.
