### ISSUE TITLE
build/dpseg/dpseg doesn't exist error during installation

### ISSUE THREAD

**Issue by alecristia** [bootphon/wordseg#7]
Error occurs while doing 
$ python setup.py install

Last 2 lines of output:
running install_data
error: can't copy 'build/dpseg/dpseg': doesn't exist or not a regular file

Working on a mac; error occurs both within miniconda and out of miniconda

**Comment by mmmaat** [comment]
Hi, is it working on mac? Did you try wordseg-dpseg? Did you try running the tests on mac?

Can you send the full command please? And the content of the directory build/dpseg? As explained in 
https://github.com/bootphon/wordseg/issues/6#issuecomment-332641590

In few days I'll commit a big change in the install process... so this issue will be outdated.

**Comment by alecristia** [comment]
Hi,

if the issue will be outdated, please ignore it. I'll try again when you
commit that big change and report back.
​

**Comment by mmmaat** [comment]
Ok I let you know.
